[all.grip]
changeset = "1666dda5607aa4d4dad0aeb8884027fd7182394e"

[all.cdl]
changeset = "6aed3743f73534a47f0ba5c915b85327ea3f0c3e"

[all.binutils]
changeset = "2846942c7c83d007106cdcf1108ceedb50e1d4ec"
branch = "binutils-2_32-branch"

[all.toolchains]
changeset = "2eab04e87cf57d09104ed273f73bfec6d4f4b2d7"

[all.verilator]
changeset = "e69c3802054e0e9bac0a9c8bd4942dde167148f1"
branch = "stable"

[cdlonly.cdl]
changeset = "8a5c219f3b50c79857bb66761b66b7546819b959"
branch = "grip"

[test.toolchains]
changeset = "4f65507a52de1861770573bd69e50353c6090698"
