[all.grip]
changeset = "ae09796754aa5a7ea7d01b18700c37e5341c0233"

[all.cdl]
changeset = "34cc83cfae195c83d92b5fb6027dd02b3b4f9ce7"

[all.binutils]
changeset = "2846942c7c83d007106cdcf1108ceedb50e1d4ec"
branch = "binutils-2_32-branch"

[all.toolchains]
changeset = "2eab04e87cf57d09104ed273f73bfec6d4f4b2d7"

[all.verilator]
changeset = "e69c3802054e0e9bac0a9c8bd4942dde167148f1"
branch = "stable"

[cdlonly.cdl]
changeset = "8a5c219f3b50c79857bb66761b66b7546819b959"
branch = "grip"

[test.toolchains]
changeset = "4f65507a52de1861770573bd69e50353c6090698"
