[all.grip]
changeset = "6209c5416371c06c48e5b7d868b8c16ff73e6c91"

[all.cdl]
changeset = "35bfa3a2251bf9c1e58e70f93310a2dcdc20b6e7"

[all.binutils]
changeset = "2846942c7c83d007106cdcf1108ceedb50e1d4ec"
branch = "binutils-2_32-branch"

[all.toolchains]
changeset = "1a1663c834b3d762444cd919912f000a5fb3aee7"

[all.verilator]
changeset = "e69c3802054e0e9bac0a9c8bd4942dde167148f1"
branch = "stable"

[cdlonly.cdl]
changeset = "8a5c219f3b50c79857bb66761b66b7546819b959"
branch = "grip"

[test.toolchains]
changeset = "4f65507a52de1861770573bd69e50353c6090698"
